Update README.md
aclc-iriga/library pull request #5
Opened 2023-05-01 14:42 UTC by benjamineke

2023-05-02 22:09 UTC, kulotsystems requested changes
Thanks @benjamineke I am requesting some changes:

2023-05-02 22:09 UTC, kulotsystems commented on README.md
> +
```suggestion
```

2023-05-02 22:09 UTC, kulotsystems commented on README.md
> +
No need for this.

```suggestion
```

2023-05-05 14:02 UTC, benjamineke commented on README.md
> +
Done

2023-05-05 14:02 UTC, benjamineke commented on README.md
> +
Done

2023-05-05 23:47 UTC, kulotsystems approved these changes
LGTM!

2023-05-05 23:47 UTC, merged